apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zichao-volume  #use your preferred name
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
